// <auto-generated />
using System;
using CopaMundo2026.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CopaDoMundo2026.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214143422_Ini")]
    partial class Ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CopaDoMundo.Models.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BandeiraSelecaoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BandeiraSelecaoB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QtdGolsSelecaoA")
                        .HasColumnType("integer");

                    b.Property<int?>("QtdGolsSelecaoB")
                        .HasColumnType("integer");

                    b.Property<string>("Rodada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelecaoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelecaoB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("CopaDoMundo.Models.Models.Palpite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("integer");

                    b.Property<int>("QtdGolsSelecaoA")
                        .HasColumnType("integer");

                    b.Property<int>("QtdGolsSelecaoB")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Palpite");
                });

            modelBuilder.Entity("CopaMundo2026.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimoAcesso")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CopaDoMundo.Models.Models.Palpite", b =>
                {
                    b.HasOne("CopaDoMundo.Models.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaMundo2026.Models.Usuario", "Usuario")
                        .WithMany("Palpites")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CopaMundo2026.Models.Usuario", b =>
                {
                    b.Navigation("Palpites");
                });
#pragma warning restore 612, 618
        }
    }
}
