// <auto-generated />
using System;
using CopaMundo2026.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CopaDoMundo2026.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219021552_Ini18_12")]
    partial class Ini18_12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CopaDoMundo.Models.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BandeiraSelecaoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BandeiraSelecaoB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Fase")
                        .HasColumnType("smallint");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QtdGolsSelecaoA")
                        .HasColumnType("integer");

                    b.Property<int?>("QtdGolsSelecaoB")
                        .HasColumnType("integer");

                    b.Property<string>("Rodada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelecaoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelecaoB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/15/M%C3%A9xico.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/09/África_do_Sul.svg",
                            DataHora = new DateTime(2026, 6, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Banorte Stadium, Cidade do México",
                            Fase = (short)0,
                            Grupo = "Grupo A",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Mexico",
                            SelecaoB = "África do Sul"
                        },
                        new
                        {
                            Id = 2,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/01/Coreia_do_Sul.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_UEFA_1NolDy2.svg",
                            DataHora = new DateTime(2026, 6, 11, 23, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Estádio Akron, Zapopan",
                            Fase = (short)0,
                            Grupo = "Grupo A",
                            Rodada = "1ª RODADA",
                            SelecaoA = "CoreiaDoSul",
                            SelecaoB = "Europa D"
                        },
                        new
                        {
                            Id = 3,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/15/Canad%C3%A1.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_UEFA_1NolDy2.svg",
                            DataHora = new DateTime(2026, 6, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "BMO Field, Toronto",
                            Fase = (short)0,
                            Grupo = "Grupo B",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Canada",
                            SelecaoB = "Europa A"
                        },
                        new
                        {
                            Id = 4,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/06/Catar.svg",
                            BandeiraSelecaoB = "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/organizations/2019/09/15/Su%C3%AD%C3%A7a.svg",
                            DataHora = new DateTime(2026, 6, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Levi's Stadium, Santa Clara",
                            Fase = (short)0,
                            Grupo = "Grupo B",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Catar",
                            SelecaoB = "Suica"
                        },
                        new
                        {
                            Id = 5,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/16/Brasil_rgYHF6Z.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/10/Marrocos.svg",
                            DataHora = new DateTime(2026, 6, 13, 19, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "MetLife Stadium, East Rutherford",
                            Fase = (short)0,
                            Grupo = "Grupo C",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Brasil",
                            SelecaoB = "Marrocos"
                        },
                        new
                        {
                            Id = 6,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/14/Haiti.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/15/Escócia.svg",
                            DataHora = new DateTime(2026, 6, 13, 22, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Gillette Stadium, Foxborough",
                            Fase = (short)0,
                            Grupo = "Grupo C",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Haiti",
                            SelecaoB = "Escócia"
                        },
                        new
                        {
                            Id = 7,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/16/Estados_Unidos.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/15/Paraguai.svg",
                            DataHora = new DateTime(2026, 6, 12, 22, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "SoFi Stadium, Inglewood",
                            Fase = (short)0,
                            Grupo = "Grupo D",
                            Rodada = "1ª RODADA",
                            SelecaoA = "EstadosUnidos",
                            SelecaoB = "Paraguai"
                        },
                        new
                        {
                            Id = 8,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/09/África_do_Sul.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_UEFA_1NolDy2.svg",
                            DataHora = new DateTime(2026, 6, 13, 1, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "BC Place, Vancouver",
                            Fase = (short)0,
                            Grupo = "Grupo D",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Australia",
                            SelecaoB = "Europa C"
                        },
                        new
                        {
                            Id = 9,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/03/Alemanha.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/14/Curaçao.svg",
                            DataHora = new DateTime(2026, 6, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "NRG Stadium, Houston",
                            Fase = (short)0,
                            Grupo = "Grupo E",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Alemanha",
                            SelecaoB = "Curaçao"
                        },
                        new
                        {
                            Id = 10,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/03/Costa_do_Marfim.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/15/Equador.svg",
                            DataHora = new DateTime(2026, 6, 14, 20, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Lincoln Financial Field, Filadélfia",
                            Fase = (short)0,
                            Grupo = "Grupo E",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Costa do Marfim",
                            SelecaoB = "Equador"
                        },
                        new
                        {
                            Id = 11,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/16/Holanda.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/03/Japao.svg",
                            DataHora = new DateTime(2026, 6, 14, 17, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "AT&T Stadium, Arlington",
                            Fase = (short)0,
                            Grupo = "Grupo F",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Holanda",
                            SelecaoB = "Japao"
                        },
                        new
                        {
                            Id = 12,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_UEFA_1NolDy2.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2018/03/10/tunisia.svg",
                            DataHora = new DateTime(2026, 6, 14, 23, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Estadio BBVA Bancomer, Guadaloupe",
                            Fase = (short)0,
                            Grupo = "Grupo F",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Europa B",
                            SelecaoB = "Tunisia"
                        },
                        new
                        {
                            Id = 13,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/15/B%C3%A9lgica.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/08/Egito.svg",
                            DataHora = new DateTime(2026, 6, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Lumen Field, Seattle",
                            Fase = (short)0,
                            Grupo = "Grupo G",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Belgica",
                            SelecaoB = "Egito"
                        },
                        new
                        {
                            Id = 14,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/01/Ir%C3%A3.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/01/Nova_Zelandia.svg",
                            DataHora = new DateTime(2026, 6, 15, 22, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "SoFi Stadium, Inglewood",
                            Fase = (short)0,
                            Grupo = "Grupo G",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Ira",
                            SelecaoB = "Nova Zelândia"
                        },
                        new
                        {
                            Id = 15,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/03/Espanha.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/08/Cabo_Verde.svg",
                            DataHora = new DateTime(2026, 6, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Mercedes-Benz Stadium, Atlanta",
                            Fase = (short)0,
                            Grupo = "Grupo H",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Espanha",
                            SelecaoB = "Cabo Verde"
                        },
                        new
                        {
                            Id = 16,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/05/Ar%C3%A1bia_Saudita.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/16/Uruguai.svg",
                            DataHora = new DateTime(2026, 6, 15, 19, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Hard Rock Stadium, Miami Gardens",
                            Fase = (short)0,
                            Grupo = "Grupo H",
                            Rodada = "1ª RODADA",
                            SelecaoA = "ArabiaSaudita",
                            SelecaoB = "Uruguai"
                        },
                        new
                        {
                            Id = 17,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/03/Fran%C3%A7a.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/03/Senegal.svg",
                            DataHora = new DateTime(2026, 6, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "MetLife Stadium, East Rutherford",
                            Fase = (short)0,
                            Grupo = "Grupo I",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Franca",
                            SelecaoB = "Senegal"
                        },
                        new
                        {
                            Id = 18,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_FIFA.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/15/Noruega.svg",
                            DataHora = new DateTime(2026, 6, 16, 19, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Gillette Stadium, Foxborough",
                            Fase = (short)0,
                            Grupo = "Grupo I",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Intercontinental 2",
                            SelecaoB = "Noruega"
                        },
                        new
                        {
                            Id = 19,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/07/15/Argentina.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/08/Argélia.svg",
                            DataHora = new DateTime(2026, 6, 16, 22, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Arrowhead Stadium, Kansas City",
                            Fase = (short)0,
                            Grupo = "Grupo J",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Argentina",
                            SelecaoB = "Argélia"
                        },
                        new
                        {
                            Id = 20,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/17/Áustria.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/03/Jordania.svg",
                            DataHora = new DateTime(2026, 6, 17, 1, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Levi's Stadium, Santa Clara",
                            Fase = (short)0,
                            Grupo = "Grupo J",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Áustria",
                            SelecaoB = "Jordânia"
                        },
                        new
                        {
                            Id = 21,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/17/Portugal.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_FIFA.svg",
                            DataHora = new DateTime(2026, 6, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "NRG Stadium, Houston",
                            Fase = (short)0,
                            Grupo = "Grupo K",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Portugal",
                            SelecaoB = "Intercontinental 1"
                        },
                        new
                        {
                            Id = 22,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/08/Uzbequistão.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/14/Colombia.svg",
                            DataHora = new DateTime(2026, 6, 17, 23, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "Estadio Azteca, Cidade do México",
                            Fase = (short)0,
                            Grupo = "Grupo K",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Uzbequistão",
                            SelecaoB = "Colômbia"
                        },
                        new
                        {
                            Id = 23,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/13/Inglaterra.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/09/16/Cro%C3%A1cia.svg",
                            DataHora = new DateTime(2026, 6, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "AT&T Stadium, Arlington",
                            Fase = (short)0,
                            Grupo = "Grupo L",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Inglaterra",
                            SelecaoB = "Croacia"
                        },
                        new
                        {
                            Id = 24,
                            BandeiraSelecaoA = "https://s.sde.globo.com/media/organizations/2019/09/08/Gana.svg",
                            BandeiraSelecaoB = "https://s.sde.globo.com/media/organizations/2019/07/16/Panamá.svg",
                            DataHora = new DateTime(2026, 6, 17, 20, 0, 0, 0, DateTimeKind.Utc),
                            Estadio = "BMO Field, Toronto",
                            Fase = (short)0,
                            Grupo = "Grupo L",
                            Rodada = "1ª RODADA",
                            SelecaoA = "Gana",
                            SelecaoB = "Panamá"
                        });
                });

            modelBuilder.Entity("CopaDoMundo.Models.Models.Palpite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("integer");

                    b.Property<int>("QtdGolsSelecaoA")
                        .HasColumnType("integer");

                    b.Property<int>("QtdGolsSelecaoB")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Palpites");
                });

            modelBuilder.Entity("CopaMundo2026.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimoAcesso")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CopaDoMundo.Models.Models.Palpite", b =>
                {
                    b.HasOne("CopaDoMundo.Models.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaMundo2026.Models.Usuario", "Usuario")
                        .WithMany("Palpites")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CopaMundo2026.Models.Usuario", b =>
                {
                    b.Navigation("Palpites");
                });
#pragma warning restore 612, 618
        }
    }
}
