using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CopaDoMundo.Models.Models
{
    public static class Constantes
    {
        public const string CatarBandeira = "https://s.sde.globo.com/media/organizations/2019/09/06/Catar.svg";
        public const string EquadorBandeira = "https://s.sde.globo.com/media/organizations/2019/07/15/Equador.svg";
        public const string HolandaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/16/Holanda.svg";
        public const string SenegalBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Senegal.svg";
        public const string EstadosUnidosBandeira = "https://s.sde.globo.com/media/organizations/2019/07/16/Estados_Unidos.svg";
        public const string InglaterraBandeira = "https://s.sde.globo.com/media/organizations/2019/09/13/Inglaterra.svg";
        public const string IraBandeira = "https://s.sde.globo.com/media/organizations/2019/09/01/Ir%C3%A3.svg";
        public const string PaisDeGalesBandeira = "https://s.sde.globo.com/media/organizations/2019/09/17/Pa%C3%ADs_de_Gales.svg";
        public const string ArgentinaBandeira = "https://s.sde.globo.com/media/organizations/2019/07/15/Argentina.svg";
        public const string ArabiaSauditaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/05/Ar%C3%A1bia_Saudita.svg";
        public const string MexicoBandeira = "https://s.sde.globo.com/media/organizations/2019/07/15/M%C3%A9xico.svg";
        public const string PoloniaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/02/Polonia_Rl0m1A5.svg";
        public const string AustraliaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/02/Australia.svg";
        public const string DinamarcaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/16/Dinamarca.svg";
        public const string FrancaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Fran%C3%A7a.svg";
        public const string TunisiaBandeira = "https://s.sde.globo.com/media/organizations/2018/03/10/tunisia.svg";
        public const string AlemanhaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Alemanha.svg";
        public const string CostaRicaBandeira = "https://s.sde.globo.com/media/organizations/2019/07/14/Costa_Rica.svg";
        public const string EspanhaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Espanha.svg";
        public const string JapaoBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Japao.svg";
        public const string BelgicaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/15/B%C3%A9lgica.svg";
        public const string CanadaBandeira = "https://s.sde.globo.com/media/organizations/2019/07/15/Canad%C3%A1.svg";
        public const string CroaciaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/16/Cro%C3%A1cia.svg";
        public const string MarrocosBandeira = "https://s.sde.globo.com/media/organizations/2019/09/10/Marrocos.svg";
        public const string BrasilBandeira = "https://s.sde.globo.com/media/organizations/2019/07/16/Brasil_rgYHF6Z.svg";
        public const string ServiaBandeira = "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/organizations/2019/09/02/Servia.svg";
        public const string CamaroesBandeira = "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/organizations/2019/09/10/Camar%C3%B5es.svg";
        public const string SuicaBandeira = "https://storage.googleapis.com/bkt-gglobo-sde-hdg-prd-sdeadmin_prod/media/organizations/2019/09/15/Su%C3%AD%C3%A7a.svg";
        public const string CoreiaDoSulBandeira = "https://s.sde.globo.com/media/organizations/2019/09/01/Coreia_do_Sul.svg";
        public const string GanaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/08/Gana.svg";
        public const string PortugalBandeira = "https://s.sde.globo.com/media/organizations/2019/09/17/Portugal.svg";
        public const string UruguaiBandeira = "https://s.sde.globo.com/media/organizations/2019/07/16/Uruguai.svg";
        public const string AfricaDoSulBandeira = "https://s.sde.globo.com/media/organizations/2019/09/09/África_do_Sul.svg";
        public const string ParaguaiBandeira = "https://s.sde.globo.com/media/organizations/2019/07/15/Paraguai.svg";
        public const string HaitiBandeira = "https://s.sde.globo.com/media/organizations/2019/07/14/Haiti.svg";
        public const string EscociaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/15/Escócia.svg";
        public const string CuracaoBandeira = "https://s.sde.globo.com/media/organizations/2019/07/14/Curaçao.svg";
        public const string CostaDoMarfimBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Costa_do_Marfim.svg";
        public const string CaboVerdeBandeira = "https://s.sde.globo.com/media/organizations/2019/09/08/Cabo_Verde.svg";
        public const string EgitoBandeira = "https://s.sde.globo.com/media/organizations/2019/09/08/Egito.svg";
        public const string NovaZelandiaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/01/Nova_Zelandia.svg";
        public const string NoruegaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/15/Noruega.svg";
        public const string ArgeliaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/08/Argélia.svg";
        public const string EuropaDBandeira = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_UEFA_1NolDy2.svg";
        public const string Intercontinental2Bandeira = "https://s.sde.globo.com/media/organizations/2025/12/03/Bandeira_FIFA.svg";
        public const string AustriaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/17/Áustria.svg";
        public const string JordaniaBandeira = "https://s.sde.globo.com/media/organizations/2019/09/03/Jordania.svg";
        public const string UzbequistaoBandeira = "https://s.sde.globo.com/media/organizations/2019/09/08/Uzbequistão.svg";
        public const string ColombiaBandeira = "https://s.sde.globo.com/media/organizations/2019/07/14/Colombia.svg";
        public const string PanamaBandeira = "https://s.sde.globo.com/media/organizations/2019/07/16/Panamá.svg";

        public const string IndefinidoBandeira = "https://s.glbimg.com/es/sde/f/organizacoes/escudo_default_65x65.png";

        public const string AfricaDoSulSelecao = "África do Sul";
        public const string AustriaSelecao = "Áustria";
        public const string PanamaSelecao = "Panamá";
        public const string ColombiaSelecao = "Colômbia";
        public const string UzbequistaoSelecao = "Uzbequistão";
        public const string JordaniaSelecao = "Jordânia";
        public const string EuropaASelecao = "Europa A";
        public const string EuropaBSelecao = "Europa B";
        public const string EuropaCSelecao = "Europa C";
        public const string EuropaDSelecao = "Europa D";
        public const string Intercontinental1Selecao = "Intercontinental 1";
        public const string Intercontinental2Selecao = "Intercontinental 2";
        public const string ArgeliaSelecao = "Argélia";
        public const string NoruegaSelecao = "Noruega";
        public const string NovaZelandiaSelecao = "Nova Zelândia";
        public const string EgitoSelecao = "Egito";
        public const string CaboVerdeSelecao = "Cabo Verde";
        public const string CostaDoMarfimSelecao = "Costa do Marfim";
        public const string CuracaoSelecao = "Curaçao";
        public const string EscociaSelecao = "Escócia";
        public const string HaitiSelecao = "Haiti";
        public const string ParaguaiSelecao = "Paraguai";
        public const string CatarSelecao = "Catar";
        public const string EquadorSelecao = "Equador";
        public const string HolandaSelecao = "Holanda";
        public const string SenegalSelecao = "Senegal";
        public const string EstadosUnidosSelecao = "EstadosUnidos";
        public const string InglaterraSelecao = "Inglaterra";
        public const string IraSelecao = "Ira";
        public const string PaisDeGalesSelecao = "PaisDeGales";
        public const string ArgentinaSelecao = "Argentina";
        public const string ArabiaSauditaSelecao = "ArabiaSaudita";
        public const string MexicoSelecao = "Mexico";
        public const string PoloniaSelecao = "Polonia";
        public const string AustraliaSelecao = "Australia";
        public const string DinamarcaSelecao = "Dinamarca";
        public const string FrancaSelecao = "Franca";
        public const string TunisiaSelecao = "Tunisia";
        public const string AlemanhaSelecao = "Alemanha";
        public const string CostaRicaSelecao = "CostaRica";
        public const string EspanhaSelecao = "Espanha";
        public const string JapaoSelecao = "Japao";
        public const string BelgicaSelecao = "Belgica";
        public const string CanadaSelecao = "Canada";
        public const string CroaciaSelecao = "Croacia";
        public const string MarrocosSelecao = "Marrocos";
        public const string BrasilSelecao = "Brasil";
        public const string ServiaSelecao = "Servia";
        public const string CamaroesSelecao = "Camaroes";
        public const string SuicaSelecao = "Suica";
        public const string CoreiaDoSulSelecao = "CoreiaDoSul";
        public const string GanaSelecao = "Gana";
        public const string PortugalSelecao = "Portugal";
        public const string UruguaiSelecao = "Uruguai";
        public const string IndefinidoSelecao = "Indefinido";

        public const string GrupoA = "Grupo A";
        public const string GrupoB = "Grupo B";
        public const string GrupoC = "Grupo C";
        public const string GrupoD = "Grupo D";
        public const string GrupoE = "Grupo E";
        public const string GrupoF = "Grupo F";
        public const string GrupoG = "Grupo G";
        public const string GrupoH = "Grupo H";
        public const string GrupoI = "Grupo I";
        public const string GrupoJ = "Grupo J";
        public const string GrupoK = "Grupo K";
        public const string GrupoL = "Grupo L";

        public const string BanorteEstadio = "Banorte Stadium, Cidade do México";
        public const string AkronEstadio = "Estádio Akron, Zapopan";
        public const string BMOEstadio = "BMO Field, Toronto";
        public const string SoFiEstadio = "SoFi Stadium, Inglewood";
        public const string LevisEstadio = "Levi's Stadium, Santa Clara";
        public const string MetLifeEstadio = "MetLife Stadium, East Rutherford";
        public const string GilletteEstadio = "Gillette Stadium, Foxborough";
        public const string BCPlaceEstadio = "BC Place, Vancouver";
        public const string NRGEstadio = "NRG Stadium, Houston";
        public const string ATTEstadio = "AT&T Stadium, Arlington";
        public const string LincolnEstadio = "Lincoln Financial Field, Filadélfia";
        public const string BBVAEstadio = "Estadio BBVA Bancomer, Guadaloupe";
        public const string MercedesEstadio = "Mercedes-Benz Stadium, Atlanta";
        public const string LumenEstadio = "Lumen Field, Seattle";
        public const string HardRockEstadio = "Hard Rock Stadium, Miami Gardens";
        public const string ArrowheadEstadio = "Arrowhead Stadium, Kansas City";
        public const string AztecaEstadio = "Estadio Azteca, Cidade do México";
    }
}
